apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.postgresql.baiju.dev
  annotations:
    service.binding/dbName: 'path={.spec.dbName}'
    service.binding/db.host: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.name: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.password: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.port: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.user: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/dbConnectionIP: 'path={.status.dbConnectionIP}'
    service.binding/dbConnectionPort: 'path={.status.dbConnectionPort}'
    service.binding/user: 'path={.status.dbCredentials},objectType=Secret'
    service.binding/password: 'path={.status.dbCredentials},objectType=Secret'
spec:
  group: postgresql.baiju.dev
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    shortNames:
      - db
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
